packages:
  - 'build-all'
  - 'connectors/absurd-sql-connector'
  - 'connectors/sqlite3-connector'
  - 'connectors/sqljs-connector'
  - 'connectors/wa-sqlite-connector'
  - 'connectors/indexeddb-connector'
  - 'examples/monopoly'
  - 'examples/todo-mvc'
  - 'examples/chinook'
  - 'examples/todo-mvc-mem'
  - 'extensions/authorization-grammar'
  - 'extensions/graphql-codegen'
  - 'extensions/graphql-grammar'
  - 'extensions/mutation-grammar'
  - 'extensions/mutation-codegen'
  - 'packages/cache-runtime-ts'
  - 'packages/codegen'
  - 'packages/codegen-api'
  - 'packages/codegen-cli'
  - 'packages/codegen-sql'
  - 'packages/codegen-ts'
  - 'packages/context-runtime-ts'
  - 'packages/crr-sqlite/instead-of-prototype/test'
  - 'packages/grammar-extension-api'
  - 'packages/instrument'
  - 'packages/integration-tests-ts'
  - 'packages/migration-runtime-ts'
  - 'packages/model-runtime-ts'
  - 'packages/mutator-runtime-ts'
  - 'packages/parse-ts'
  - 'packages/query-runtime-ts'
  - 'packages/react'
  - 'packages/runtime-ts'
  - 'packages/schema'
  - 'packages/schema-api'
  - 'packages/sql-ts'
  - 'packages/vscode'
